import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Tomás Medina",
  description: "Generated by create Juan Segundo Martínez",
};

import { Oswald } from "next/font/google";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";

const oswald = Oswald({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="icon" href="./icon.ico" sizes="any" />
      </head>
      <body
        className={`text-white w-full max-w-[1350px] mx-auto ${oswald.className}`}
      >
        <Header />
        <main className="flex w-full flex-col items-center justify-between text-white blob-background">
          <Providers>{children}</Providers>
          <Toaster />
        </main>
        <Footer />
      </body>
    </html>
  );
}
